version: "3.4"
services:
  nginx:
    image: "nginx:latest"
    ports: 
      - "2001:2001"
    container_name: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./nginxlogs:/var/log/nginx"
    depends_on:
      - app1
      - app2
  app1:
    container_name: nginx-app1
    environment: 
      - "ASPNETCORE_URLS=http://+:5000"
    build: ../app1
  app2:
    container_name: nginx-app2
    environment: 
      - "ASPNETCORE_URLS=http://+:5003"
    build: ../app2
